# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Valentin Lachand-Pascal
about:               PhD Student in computer science - Technology teacher in secondary school
tagline:             ''
description:         ''
url:                 ''
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Valentin Lachand-Pascal
  url:               https://valentin.lachand.net
  email:             valentin@lachand.net

# Custom vars
version:             1.0.0
